---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/ansible-controller
  type: udm.Application
  lastVersion: 1.0.0
  children:
  - name: 1.0.0
    type: udm.ProvisioningPackage
    deployables:
    - name: ansible-controller-NIC
      type: azure.NetworkInterfaceSpec
      location: '{{location}}'
      networkInterfaceTags:
        demo: digital.ai
        env: '{{env}}'
      networkSecurityGroupName: ansible-controller-NSG
      ipConfigurations:
      - name: ansible-controller-ip
        type: azure.NetworkInterfaceIPConfigurationSpec
        virtualNetworkName: ansible-controller-VNET
        subnet: ansible-subnet
        publicIpAddress: ansible-controller-publicIP
    - name: ansible-controller-publicIP
      type: azure.PublicIpAddressSpec
      location: '{{location}}'
      publicIpAddressTags:
        env: '{{env}}'
    - name: ansible-controller-VNET
      type: azure.VirtualNetworkSpec
      location: '{{location}}'
      virtualNetworkTags:
        demo: digital.ai
        env: '{{env}}'
      addressPrefixes:
      - 10.0.0.0/16
      subnets:
      - name: ansible-subnet
        type: azure.SubnetSpec
        subnetTags:
          demo: digital.ai
          env: '{{env}}'
        addressPrefix: 10.0.0.0/24
        networkSecurityGroupName: ansible-controller-NSG
    - name: ansible-controller-NSG
      type: azure.NetworkSecurityGroupSpec
      location: '{{location}}'
      networkSecurityGroupTags:
        demo: digital.ai
        env: '{{env}}'
      securityRules:
      - name: ssh_rule
        type: azure.SecurityRuleSpec
        protocol: Tcp
        sourcePortRange: '*'
        destinationPortRange: "22"
        sourceAddressPrefix: '*'
        destinationAddressPrefix: '*'
        access: Allow
        priority: "123"
        direction: Inbound
    - name: ansible-host
      type: azure.VirtualMachineSpec
      boundTemplates:
      - Applications/ansible-controller/1.0.0/ansible-host-template
      provisioners:
      - name: ansible-setup
        type: script.provisioner.Script
        hostTemplate: Applications/ansible-controller/1.0.0/ansible-host-template
        file: !file "artifacts/Applications/ansible-controller/1.0.0/ansible-instance/ansible-setup/provision_ansible.sh"
      virtualMachineTags:
        demo: digital.ai
        env: '{{env}}'
      location: '{{location}}'
      sku: 18.04-LTS
      version: latest
      osDiskName: osdisk
      osStorageAccountName: ansiblecontrolersa
      caching: ReadWrite
      computerName: ansible-host-vm
      adminUserName: AzureUser
      adminPassword: connectedWithAzure3579
      enableLinuxConfiguration: "True"
      disablePasswordAuthentication: "False"
      publicKeys:
        /home/AzureUser/.ssh/authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVwrBFb6qlKoj64PRfTwM6dNxugS8lvbriWBmp3Xo/F7e4JaJyOqErurvQ/cviiWiwexoLE1SxnyaCWin5uBkcNMcpjRtIUaSeKVht5kVqFvxe7uXjqcggUYbWFGhh91fGqlddjYmGpN6Tue8OLmhbiq6tF8SRncUExT+Gpj4Bn5Pe7XhHEuN0MFiN4bK+bEBKQkzKE7jgbEWmmc5/pwrsEEsuwaxUl6yoWbIq3mZoy9u5mUK2HFFQ9Nus9mJEiDVYtATO7aL6/gOeBzhkBO+x9UPV8B9lLjdSoWwmCkxFNfQuTlWoPERG1rqrX++gocpB8dJb1SKaZvUf65rRmOZ1
          AzureUser@ansible-host
      networkInterfaces:
      - ansible-controller-NIC
    - name: ansiblecontrolersa
      type: azure.StorageAccountSpec
      location: '{{location}}'
      storageAccountTags:
        demo: digital.ai
        env: '{{env}}'
    templates:
    - name: ansible-host-template
      type: template.overthere.SshHost
      instanceName: ansible-controller-{{%instanceId%}}-host
      childTemplates:
      - name: ansible-controler-template
        type: template.ansible.Controller
        instanceName: defaultAnsibleController
        ansiblePlaybookPath: /usr/bin/ansible-playbook
        ansibleGalaxyPath: /usr/bin/ansible-galaxy
      tags:
      - ansible_roles_not_applied
      os: UNIX
      connectionType: SUDO
      address: '{{%publicIp%}}'
      username: AzureUser      
      privateKeyFile: ../.ssh/xl-azure-workshop2
      sudoUsername: root
