---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- directory: Environments/test
  children:
  - name: azure test
    type: udm.Environment
    members:
    - Infrastructure/azure cloud connection
    dictionaries:
    - Environments/test/azure test configuration
  - name: azure test configuration
    type: udm.Dictionary
    entries:
      location: France Central
      env: test
